{% set name = "protal" %}
{% set version = "0.1.1a" %}

package:
  name: {{ name }}
  version: {{ version }}

{# source:
  url: https://github.com/4less/protal/archive/refs/tags/{{version}}.tar.gz
  sha256: 4772fd3c6d6b95b8029f1b14bd100ed89846d65b #}

source:
  git_url: https://github.com/4less/protal.git
  git_rev: 2115495a33351c29bbb91582b95f8bf97cac9924  # specific commit hash

build:
  skip: true  # [osx]
  number: 0
  run_exports:
    - {{ pin_subpackage('protal', max_pin="x.x") }}

requirements:
  build:
    - cmake
    - ninja
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - pkg-config
    - python >=3
  host:
    - libgomp      # [linux]
    - llvm-openmp  # [osx]
    - zlib
  run:
    - python >=3
    - pigz
    - libgomp      # [linux]
    - llvm-openmp  # [osx]

test:
  commands:
    - protal --help

about:
  home: "https://github.com/4less/protal"
  dev_url: "https://github.com/4less/protal"
  license: MIT
  license_family: MIT
  license_file: "license.txt"
  summary: "Reference-based metagenomic analysis."
  description: |
    Protal is a computational tool for taxonomic profiling and strain-resolved analyses of bacterial communities from 
    metagenomic shotgun sequencing data (short-reads). Following a reference-based approach, protal uses the same
    120 universal marker genes GTDB uses to build their phylogeny (TIGRFAM, PFAM) and thus integrates well with other
    tools working in the GTDB taxonomy space.
