{% set name = "protal" %}
{% set version = "0.1.0-alpha" %}

package:
  name: {{ name }}
  version: {{ version }}  # Update version accordingly

source:
  # git_url: https://github.com/4less/protal.git
  # git_rev: alpha
  url: https://github.com/4less/protal/archive/refs/tags/{{version}}.tar.gz
  sha256: 30f11508c3a110e3d121dbaba2c1e8991cf506f3271a2b6655ea3301e51a2801

requirements:
  build:
    - cmake
    - make
    - gcc_linux-64 >=14.2.0
    - gxx_linux-64 >=14.2.0
    - libgomp >=14.2.0
    - zlib
  run:
    - python>=3
  test:
    commands:
      - protal --help

channels:
  - conda-forge    # High priority channel
  - bioconda


about:
  home: https://github.com/4less/protal/
  dev_url: https://github.com/4less/protal/
  license: MIT
  license_family: MIT
  license_file: "license.txt"
  summary: "Reference-based metagenomic analysis"
  description: |
    Protal is a computational tool for taxonomic profiling and strain-resolved analyses of bacterial communities from 
    metagenomic shotgun sequencing data (short-reads). Following a reference-based approach, protal uses the same
    120 universal marker genes GTDB uses to build their phylogeny (TIGRFAM, PFAM) and thus integrates well with other
    tools working in the GTDB taxonomy space. 
